version: '3'

services:
  sci_bot:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: kreczko/sci_bot
    domainname: foo.bar
    hostname: fast
    network_mode: "host"
    working_dir: /app/user
    entrypoint:
      - /usr/local/bin/sci_bot
      - --listen

  webhook_forwarder:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: kreczko/sci_bot
    domainname: foo.bar
    hostname: fast
    network_mode: "host"
    working_dir: /app/user
    entrypoint:
      - /usr/local/bin/sci_bot
      - --forward

  dev:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: kreczko/sci_bot
    environment:
      DEBUG: 1
    domainname: foo.bar
    hostname: fast
    network_mode: "host"
    volumes:
      - .:/app/user
    working_dir: /app/user
    entrypoint:
      - /usr/local/bin/sci_bot
      - --listen
