version: '3'

services:
  sci_bot:
    build:
      dockerfile: docker/Dockerfile
      context: .
    image: kreczko/sci_bot
    environment:
      DISPLAY: ${DISPLAY}
      TERM: ${TERM}
    tty: true
    stdin_open: true
    domainname: foo.bar
    hostname: fast
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/code
    working_dir: /code
    entrypoint:
      - tail
      - -f
      - "/dev/null"
